# Generated by Django 5.2.9 on 2026-01-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
        ('services', '0002_servicedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='service_details',
            field=models.ManyToManyField(blank=True, to='services.servicedetail'),
        ),
    ]
