# Generated by Django 5.2.9 on 2026-01-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_service_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='district',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
