# Generated by Django 5.2.9 on 2026-01-02 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_approved_at'),
        ('listings', '0003_alter_listing_district'),
    ]

    operations = [
    ]
