# Generated by Django 5.2.9 on 2026-01-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_servicedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedetail',
            name='question',
            field=models.CharField(blank=True, default='Umumiy', max_length=200),
        ),
    ]
