# Generated by Django 5.2.9 on 2026-01-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatthread_client_alter_chatthread_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatthread',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Ochiq'), ('CLOSED', 'Yopiq')], default='OPEN', max_length=10),
        ),
    ]
