# Generated by Django 5.2.9 on 2026-01-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_registrationtoken_user_telegram_id_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Mijoz'), ('PROVIDER', 'Usta'), ('ADMIN', 'Administrator')], default='CLIENT', max_length=20),
        ),
    ]
